### ISSUE TITLE
Support individual ttl

### ISSUE THREAD

**Issue by superdweebie** [zoopcommerce/juggernaut#2]
To be more versitile, juggernaut should support setting ttl for a cached item as part of the `setItem` call.

**Comment by joshystuart** [comment]
A problem with this is that the way filesystem caches work they use the "time modified" `filemtime($file)` for ttl. I was going to work around this limitation by putting the expiration time as the first line of the file and just split it out, but it adds a bit more overhead to the process.

Not sure if you have any ideas to overcome that.

**Comment by superdweebie** [comment]
I see your point. The work around you describe is what the Doctrine Cache does. Given that Juggernaut is trying to be really fast, I think what you have done is better. If there is a strong need to vary ttl, then separate cache instances can be created.
