### ISSUE TITLE
Remove plural from namespace

### ISSUE THREAD

**Issue by superdweebie** [zoopcommerce/juggernaut#5]
`Zoop\Juggernaut\Adapters` should probably be `Zoop\Juggernaut\Adapter`

**Comment by joshystuart** [comment]
Ah yep. Will do.

**Comment by superdweebie** [comment]
I have it open now. I can do it if you like.

**Comment by joshystuart** [comment]
Cool. I have to update the app code too.

**Comment by superdweebie** [comment]
Handled by #8
