### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by superdweebie** [zoopcommerce/juggernaut#7]
I think we should tag a version, even if it's 0.0.1 or something like that. If we keep using `dev-master` we'll get into the version mess like I did with the Sds repos and the api.

**Comment by joshystuart** [comment]
Yeah. Damn I've been meaning to do that.

**Comment by superdweebie** [comment]
Do you mind if I go ahead and tag 1.0?

**Comment by joshystuart** [comment]
By all means. I was going to do it the other day but got sidetracked.

**Comment by superdweebie** [comment]
Done
